### ISSUE TITLE
[BUG] Error code 500 Internal error

### ISSUE THREAD

**Issue by Asg1109** [immich-app/immich#1158]
**Describe the bug**

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [ ] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
- Phone OS [iOS, Android]: `<version>`
- Server Version: `<version>`
- Mobile App Version: `<version>`

**Additional context**

**Comment by alextran1502** [comment]
I cannot help you without the required documents
