### ISSUE TITLE
[BUG] Album information does not update when sliding images

### ISSUE THREAD

**Issue by Zlendy** [immich-app/immich#1376]
**Describe the bug**
Inside the column "Info", the section "APPEARS IN" does not update with the matching album when sliding images.

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file. (This is not necessary)
- [ ] I have included my redacted `.env` file. (This is not necessary)
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Click on any image to open it in a maximized view
2. Click the button labeled "Info"
3. Look at the value of the section "APPEARS IN"
4. Slide left or right to any other image
5. The section will not update to the new value

**Expected behavior**
The value will refresh with the correct one

**Screenshots**
This is what I mean in the Description
![image](https://user-images.githubusercontent.com/22578704/213884096-e818d51f-68f5-4d60-911c-a082a882aee8.png)

**System**
- Server Version: `v1.42.0`

**Additional context**
This bug can be reproduced from the [demo instance](https://demo.immich.app/photos).
It was not present in the docker image `altran1502/immich-web:1255` and prior versions.
From the research I have made, the server used to fetch this value from the API every time an image was loaded, but this is no longer happening.

**Comment by Zlendy** [comment]
If this is not an intended behaviour, I would like to fix it myself and submit a PR.

**Comment by alextran1502** [comment]
@Zlendy Yes please and thank you

**Comment by Zlendy** [comment]
> @Zlendy Yes please and thank you

Done!
