### ISSUE TITLE
[BUG] Unable to select a picture from the bottom of the album as cover if album is bigger then ~500 pictures

### ISSUE THREAD

**Issue by SitramSoft** [immich-app/immich#1442]
**Describe the bug**
Unable to select a picture from the bottom of the album as cover for an album that has more then ~500 pictures in the web interface.
When I scroll past first ~500 pictures and try to select one as a cover for the album, instead of selecting it, it will open the picture and the "Done" button remains grayed out.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file. -> N/A
- [x] I have included my redacted `.env` file. -> N/A
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Open an album in web interface
2. Click on 'Set album cover'
3. Scroll down past the first ~500 pictures
4. Click on a picture
5. Picture is opened and the 'Done' button remains grayed out.

**Expected behavior**
Picture is selected and the 'Done' button is active.

**Screenshots**
Normal behavior:
![image](https://user-images.githubusercontent.com/8177290/215093027-4ba8c764-3356-4ab0-bf3b-af02dcbdb8f1.png)

Bug:
![image](https://user-images.githubusercontent.com/8177290/215092806-4ec0b909-a422-463a-b141-160886933bb3.png)

**System**
- Phone OS [iOS, Android]: `Android`
- Server Version: `1.42.0`
- Mobile App Version: `1.42.0 build 65`

**Additional context**
I run immich docker on a VM running Ubuntu 22.04.1 LTS in Proxmox 7.3-4

**Comment by SitramSoft** [comment]
Issue remains even in Server Version v1.51.2

**Comment by michelheusschen** [comment]
I think this was the bug where the album would still show underneath the album cover selector. Should've been fixed a while back
