### ISSUE TITLE
[BUG] [Web] Deleting photos results to Console Error but photos were successfully deleted in the server

### ISSUE THREAD

**Issue by jbalcao** [immich-app/immich#1531]
**Describe the bug**
Tried deleting photos in the web and will result to this error message after clicking Ok in the prompt. But after refreshing the page, the photos were successfully deleted.

![signal-2023-02-03-11-39-28-206.png](https://user-images.githubusercontent.com/88887245/216507163-2bf81c7b-5ab4-4ef7-bdc1-091088a149e0.png)

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [ ] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Select photos
2. Click delete button
3. Error message will appear

**Expected behavior**
No error message since photos were deleted successfully

**Screenshots**

**System**
- Phone OS [iOS, Android]: `<version>`
- Server Version: 1.44 latest
- Mobile App Version: `<version>`

**Additional context**

**Comment by alextran1502** [comment]
Confirmed, thank you!
