### ISSUE TITLE
[FEATURE] Edit user on the web 

### ISSUE THREAD

**Issue by Nonobis** [immich-app/immich#220]
**Describe the bug**
Can't edit user in web

**Task List**
- [ ] I have read thoroughly the README setup and installation instructions.
- [ ] If my setup is different, I have included my docker-compose file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Go to Backend / User Page
2. Click on Edit
3. No action done :)

**Expected behavior**
A  clean/simple popup for editing user when you have time :)

**Desktop (please complete the following information):**
 - OS: Unraid
 - Docker Compose Plugin + Docker File

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 9 Pro
 - OS: Android
 - Version 11

**Additional context**
None
