### ISSUE TITLE
[BUG] Upload sames images multiples times create duplicates

### ISSUE THREAD

**Issue by Nonobis** [immich-app/immich#248]
**Describe the bug**

On web, when uploading same images multiple times, the interface display multiples times the pictures.
I don't know if image are physycally duplicated, on only on display.

**Task List**
- [X] I have read thoroughly the README setup and installation instructions.
- [X] If my setup is different, I have included my docker-compose file.
- [ ] I have included my redacted `.env` file.
- [X] I have included information on my machine, and environment.

**To Reproduce**
1. Go to Web
2. Click on Upload
3. Upload x pictures
4. Wait ...
5. Return to 2. and re-upload same images

**Expected behavior**
No duplicate images ....

**Screenshots**
![image](https://user-images.githubusercontent.com/3251510/175108755-c8637afc-ed1b-42b0-a47c-006b0a879341.png)
![image](https://user-images.githubusercontent.com/3251510/175108890-4d09d0e4-2ad7-49a3-bf50-fea34938bddf.png)

**Desktop (please complete the following information):**
 - OS : Unraid
 - Latest docker image

**Comment by alextran1502** [comment]
When you refresh the page, is the duplicated image still there?

**Comment by alextran1502** [comment]
Hmm interesting, so that means the image is duplicated physically. So before uploading the file to the server, the web will check for this format

```bash
web-{file_name}-{last_modified_date_in_utc}
```

If the file is modified or has different names, then it will upload. 

Can you help me check the file?

**Comment by alextran1502** [comment]
From one father to another, happy late father's day!

**Comment by Nonobis** [comment]
i think i have understand the problem... i have made a first upload of this pictures. The date/time of file was wrong, so i made a quick program for extract OrginalDatetime from the metadata and re-apply it to files before re-uploading (as there is no deletion for now). 

It was my assumption your where calculating an hash of file for testing if picture was truly unique.  (i use this nuget in .Net CoenM.ImageSharp.ImageHash, for calculating hash in a personal program using image....). 

PS : For french translation, i will make a pr when #246 will be merged :)

**Comment by Nonobis** [comment]
![image](https://user-images.githubusercontent.com/3251510/175213219-165da62d-b339-4466-b564-1d5272f755ab.png)

**Comment by Nonobis** [comment]
i have found that duplicate image have double extension in web ui *.jpg.jpg i don't known if it can help....

**Comment by Nonobis** [comment]
![image](https://user-images.githubusercontent.com/3251510/175214638-7d673abe-2fae-4f34-8c94-a63f5a94f859.png)
![image](https://user-images.githubusercontent.com/3251510/175215134-bb7cd63a-e8eb-4e9d-9cc2-25764a9ea856.png)

**Comment by SirBogner** [comment]
Regarding the jpg.jpg extension: It seems to me that images uploaded from the web create a double .jpg extensions and the images uploaded from the app creates a single

**Comment by alextran1502** [comment]
> i think i have understand the problem... i have made a first upload of this pictures. The date/time of file was wrong, so i made a quick program for extract OrginalDatetime from the metadata and re-apply it to files before re-uploading (as there is no deletion for now). 
> 
> 
> 
> It was my assumption your where calculating an hash of file for testing if picture was truly unique.  (i use this nuget in .Net CoenM.ImageSharp.ImageHash, for calculating hash in a personal program using image....). 
> 
> 
> 
> PS : For french translation, i will make a pr when #246 will be merged :)

This can be a solution, related to the deduplication on the server.

**Comment by m4rkv5** [comment]
When i have the webview open an upload images via iOS, i see duplicates in the web view. When I download them, the files have different IDs. After a page refresh i don't see duplicates any longer.

V 1.13.0
