### ISSUE TITLE
[BUG] Edit Button in the admin area does nothing

### ISSUE THREAD

**Issue by Morethanevil** [immich-app/immich#443]
**Describe the bug**
I can not edit users that i created in the adminpanel. The edit button does nothing. It is impossible to delete a user, or to change the password, name etc.... 

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [ x ] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Go to 'adminpanel'
2. Click on ''the edit button'
3. See error, nothing happens

**Expected behavior**
A menu where i can choose to delete a user, or edit the password, name etc....

**Screenshots**

**System**
- Server Version: `1.20.3>`

**Comment by alextran1502** [comment]
Not a bug, not implemented yet. On the to do list.

Thank you for reporting
