### ISSUE TITLE
[BUG] Scrolling through pictures with Left/Right keyboard buttons not accurate

### ISSUE THREAD

**Issue by BackedUpBooty** [immich-app/immich#514]
**Describe the bug**
Immich v1.25.0, Synology DS920+, DSM7.1, installed with docker-compose. Other than the machine learning which my CPU doesn't support, rest of immich works well except for:

When accessing immich through browser on desktop and clicking a photo thumbnail, it brings up the larger image. When pressing left or right arrow keys on the keyboard brings up older or newer photos, but not in step order (it seems like it's almost a 'chapter' type of scroll, as it will always go to a specific photo, no matter which one I start from, but it's not by days or any other constant I can tell). 

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file. N/A
- [ ] I have included my redacted `.env` file. N/A
- [x] I have included information on my machine, and environment. 

**To Reproduce**
1. Install Immich v1.25.0 via docker (without machine learning container to replicate my exact setup)
2. Access immich web via browser (IP:port)
3. Click a photo after uploading (I have 1200 photos uploaded)
4. Hit left or right arrow keys on keyboard
5. Same for Chrome, Edge and Firefox

**Expected behavior**
Left or right arrow keys scroll through photos by single step, not multiple.

**Screenshots**

**System**
- Server Version: `v1.25.0`

**Comment by alextran1502** [comment]
I noticed this as well, I think the button will need to be debounced.
