### ISSUE TITLE
[BUG] Uploading videos from iCloud Shared Albums causes metadata issues

### ISSUE THREAD

**Issue by TCVinNYC** [immich-app/immich#552]
**Describe the bug**
After the phone uploads a Cinematic Video, Immich plays it back in a lower resolution on both the web & app (assuming it's the conversion of MOV to MP4). When attempting to download, it downloads the lower-resolution version on web and mobile. This download also does not have the metadata as the original. Immich also organizes it on a different date category.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I thoroughly read the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Have the phone upload the Cinematic Video.
2. Watch on mobile or the web.
3. Attempt to look at metadata and download.
4. Compare the size and metadata differences.

**Expected behavior**
Immich should download the original video when requested. It should also have metadata on the converted video and organize it with the proper date.

**Screenshots**
Added screenshots of Immich metadata vs Photos app.

**System**
- iPhone 13 Pro Max, iOS 16 beta 7
- Server Version: `1.26.0`
- Mobile App Version: `1.26.0 build 51`
- Unraid Server 6.10.3, Immich running with Portainer-CE 2.14.2
[docker-compose.txt](https://github.com/immich-app/immich/files/9449768/docker-compose.txt)
[my .env.txt](https://github.com/immich-app/immich/files/9449769/my.env.txt)

**Additional context**
Links to metadata comparison.

Original Video
https://www.metadata2go.com/result/71aedb6e-cb57-4df2-bda7-29ac142cdde8

Downloaded Video from Immich Web
https://www.metadata2go.com/result/581b9b40-9174-4e76-9295-00615f25afb4

Video Links (FullSizeRender is the original Cinematic video, while the other is Immich's)
https://drive.google.com/drive/folders/1_nYIfNivxOX84uPoFTwoKnwuj-mPj_lU?usp=sharing

**Comment by panoti** [comment]
Hi @TCVinNYC, what downloader have you used to download? I've tried upload your video and download it. Both files are the same hash.

**Comment by TCVinNYC** [comment]
Microsoft Edge 104.0.1293.70

**Comment by TCVinNYC** [comment]
We found out that uploading assets from iCloud Shared Albums seems causes file name and metadata issues. The filename is read as "FullSizeRender" and the date + time is from the last modified date of the said Shared Album.

For now the fix is to not select any Shared Albums from iCloud when uploading to Immich.

**Comment by alextran1502** [comment]
> Every Photo which I upload with the iOS app that has been edited within the photos app gets the title FullSizeRender.jpg. I can reproduce it. Unedited Photos keep their original file names.
> 
> 
> 
> iOS 1.37.1 build.74
> 
> Server v1.37.0

I think this is the expected behavior of the edited file

**Comment by m4rkv5** [comment]
But the name in the photos app doesn't change when you edit a photo. 50% of my library has the the name Fullsizerender.jpg. When I download photos all have the same name.

**Comment by mckennajones** [comment]
I'm noticing the same behavior. In addition to iOS photos that I have edited, I notice the same `fullSizeRender` name for photos that have been saved to my apple photos library from Google Photos.

**Comment by logaritmisk** [comment]
I have the same issue, I also use Pixelmators Photo app to edit my photos so almost all of the photos I want to backup is named `FullSizeRender.jpg`.

This gave my another issue as well. As the storage template use the date and filename only one photo per day could be saved as the where overwritten (ex. if I have taken two photos first of January and both had been edited, they would be saved to `2023/2023-01-01/FullSizeRender.jpg`).

I found a workaround by changing the storage template to include the timestamp as well. But this feels awkward and I'm not sure this will make the issue go away. There is a possibility that I have two photos taken within them same second.

**Comment by benjamonnguyen** [comment]
Just to clarify the expected behavior, should I expect the download option to download the original media? I am getting the transcoded video file instead.

**Comment by alextran1502** [comment]
I belive this is now fixed
