### ISSUE TITLE
[BUG] Storage used up before even uploading images

### ISSUE THREAD

**Issue by ShockedCoder** [immich-app/immich#589]
**Describe the bug**
Fresh docker of Immich already has 9GB out of 15GB used

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [X] I have read thoroughly the README setup and installation instructions.
- [X] I have included my [`docker-compose`](https://github.com/immich-app/immich/files/9491059/docker-compose.yml.txt) file.
- [X] I have included my redacted [`.env`](https://github.com/immich-app/immich/files/9491052/dotenv.txt) file.
- [X] I have included [information](https://linux-hardware.org/?probe=fad575d0fa) on my machine, and environment.

**To Reproduce**
1. Create empty folder
2. Follow README
3. `docker-compose up`
4. Login
5. See storage is already used up

**Expected behavior**
The used-up storage to be 0GB, as I hadn't even logged in yet.

**Screenshots**
![storage used and app version](https://user-images.githubusercontent.com/40272709/188485344-715de112-f916-4c9f-ae5d-4224e96afe64.png)

**System**
- Phone OS [iOS, Android]: None
- Server Version: 1.26.0
- Mobile App Version: None

**Additional context**
I can't figure out how to just increase the allocated storage to the app or probe what files are using this storage.

**Comment by bo0tzz** [comment]
The reported storage shows how much space is used/free in your library folder, which in this case is on your root partition. It looks like that partition is only 15GB large. From the `df` output in your probe: `/dev/mapper/XXXXXXXXXXXXXXXXXX xfs        15G  9.3G  5.8G  62% /`. However, the disk that you assigned to the VM is a more appropriate 200GB. Growing the root partition should solve your issue. You'll need to google how to do that for your distro, but it should be pretty straightforward.

**Comment by alextran1502** [comment]
Closing as this problem is platform specific.

**Comment by ShockedCoder** [comment]
I found the dormant 200GB
![I found where the 200GB went](https://user-images.githubusercontent.com/40272709/188499598-f313e04e-5e3d-41aa-9c75-87dfab0564e2.png "I found where the 200GB went")

I have no idea why Proxmox formatted it like this.

Thanks for pointing it out, bo0tzz.

**Comment by srvprivate** [comment]
This issue is present on UNRAID as well. I followed all the steps per documentation, and it starts out with about 465GB of used storage with 1.8TB as the cap. This is super odd....I've deleted everything over and over and still can't get it down to 0
