### ISSUE TITLE
[BUG] Backup process loses progress when phone sleeps

### ISSUE THREAD

**Issue by godismyjudge95** [immich-app/immich#600]
**Describe the bug**
Backup process loses progress, restarts, and resets the counters when the phone goes to sleep.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file. - latest docker-compose file from git
- [x] I have included my redacted `.env` file. - no special .env or environment variables
- [x] I have included information on my machine, and environment. - Docker compose setup, on Synology NAS, with NGINX reverse proxy in front

**To Reproduce**
1. Install an the Immich app - in my case 1.27
2. Setup the backup and let the backup process complete entirely
3. Uninstall the Immich app
4. Install the Immich app again
5. Setup the backup process in the exact same way
6. While on the backup screen take note of the remainder number
7. Wait until a few items have uploaded
8. Turn off the phone's screen (using power button or let the phone go to sleep)
9. Wake the phone and unlock to go back to the same backup screen
10. This time the remainder number will jump back up to some higher number and the backup process will restart on media that has already been uploaded

**Expected behavior**
Immich should be able to remember it's spot regardless of whether the phone goes to sleep.  Also

**System**
- Phone OS [iOS, Android]: `Android 13`
- Server Version: `1.27.0`
- Mobile App Version: `1.27.0 build.37`

**Additional context**
I have a feeling the key to this is that I uninstalled the app and re-installed it.  Something about the de-duplication/upload progress I think is not saving when re-initializing the local app database.

**Comment by alextran1502** [comment]
Here is my guess, since you are installing from the APK, the device ID might change upon installation (I know it sounds weird, but there are such things). Since the device ID is used to perform the operation of finding the photos/videos that have not been presented in the database, different device IDs will cause this bug.

Can you try the new version of the app from the Google Play store when it is released?

**Comment by godismyjudge95** [comment]
That make a lot of sense.  Yes I will re-install from the app store once the update is out and try it out.

**Comment by alextran1502** [comment]
The new version is release, can you help me check this issue and let me know if it still persists

**Comment by alextran1502** [comment]
Closing as expected issue with installing the app from APK
