### ISSUE TITLE
[BUG] Images in incorrect order

### ISSUE THREAD

**Issue by gabriel-gfs** [immich-app/immich#676]
**Describe the bug**
These two pictures have a certain timestamp they appear in the wrong order in immich.
![20220819-IMG_9066](https://user-images.githubusercontent.com/36446511/189529145-79cfae4b-a4b5-46ad-b181-e49010b86a6f.jpg)

![20220819_121927](https://user-images.githubusercontent.com/36446511/189529147-41c69366-1028-44a1-994b-fe06b9f80526.jpg)

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included information on my machine, and environment.

```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:latest
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:80
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```

**To Reproduce**

**Expected behavior**
The images appear in correct order.

**System**
- Phone OS: Android 12/12L
- Server Version: v1.28.2

**Comment by panoti** [comment]
Hi @gabriel-gfs, the file `20220819-IMG_9066` is not found. Can you re-upload again?

**Comment by alextran1502** [comment]
Hi @gabriel-gfs Here are the two timestamp I have after uploading by the web app

# Image 1
<img width="661" alt="Screen Shot 2022-09-12 at 23 41 39" src="https://user-images.githubusercontent.com/27055614/189810613-d842e197-1146-4205-965e-9f66bacaf6e2.png">

## EXIF
<img width="352" alt="Screen Shot 2022-09-12 at 23 46 57" src="https://user-images.githubusercontent.com/27055614/189811136-21942e3b-33b4-404b-8908-8d639ca1309b.png">


## TIFF
<img width="343" alt="Screen Shot 2022-09-12 at 23 45 55" src="https://user-images.githubusercontent.com/27055614/189810995-bf1ecb81-6511-4db3-bff1-3bbaf44b9353.png">

# Image 2
<img width="1311" alt="Screen Shot 2022-09-12 at 23 41 47" src="https://user-images.githubusercontent.com/27055614/189810617-bf94a6a1-0b05-41c9-a7a9-802a42fd65d4.png">

## EXIF
<img width="308" alt="Screen Shot 2022-09-12 at 23 46 30" src="https://user-images.githubusercontent.com/27055614/189811079-55d44105-e4d0-44c5-8878-2ddcef4eeebd.png">

## TIFF
<img width="249" alt="Screen Shot 2022-09-12 at 23 46 19" src="https://user-images.githubusercontent.com/27055614/189811047-e2cc0a5b-b2fb-43d4-8fb4-a80d0f7ee989.png">

Which one do you expect to be the correct one?

@panoti I think this is the problem, you faced, correct?

**Comment by panoti** [comment]
@alextran1502 same as me. It comes from time zone problem. But idk whether @gabriel-gfs he's talking about that or not.

**Comment by gabriel-gfs** [comment]
> Hi @gabriel-gfs Here are the two timestamp I have after uploading by the web app
> 
> # Image 1
> <img alt="Screen Shot 2022-09-12 at 23 41 39" width="661" src="https://user-images.githubusercontent.com/27055614/189810613-d842e197-1146-4205-965e-9f66bacaf6e2.png">
> 
> ## EXIF
> <img alt="Screen Shot 2022-09-12 at 23 46 57" width="352" src="https://user-images.githubusercontent.com/27055614/189811136-21942e3b-33b4-404b-8908-8d639ca1309b.png">
> 
> ## TIFF
> <img alt="Screen Shot 2022-09-12 at 23 45 55" width="343" src="https://user-images.githubusercontent.com/27055614/189810995-bf1ecb81-6511-4db3-bff1-3bbaf44b9353.png">
> 
> # Image 2
> <img alt="Screen Shot 2022-09-12 at 23 41 47" width="1311" src="https://user-images.githubusercontent.com/27055614/189810617-bf94a6a1-0b05-41c9-a7a9-802a42fd65d4.png">
> 
> ## EXIF
> <img alt="Screen Shot 2022-09-12 at 23 46 30" width="308" src="https://user-images.githubusercontent.com/27055614/189811079-55d44105-e4d0-44c5-8878-2ddcef4eeebd.png">
> 
> ## TIFF
> <img alt="Screen Shot 2022-09-12 at 23 46 19" width="249" src="https://user-images.githubusercontent.com/27055614/189811047-e2cc0a5b-b2fb-43d4-8fb4-a80d0f7ee989.png">
> 
> Which one do you expect to be the correct one?
> 
> @panoti I think this is the problem, you faced, correct?

![image](https://user-images.githubusercontent.com/36446511/189857908-3f504963-564e-4f49-b958-e5bdee73cfa9.png)
This is the order that is displayed in the timeline of immich, ergo the picture with the later timestamp is displyed earlier than the picture wiht the earlier timestamp.

**Comment by alextran1502** [comment]
@gabriel-gfs I think the order is correct, since each image grid starting to display the latest in the day and progress to display the later one.

**Comment by alextran1502** [comment]
Close with the reason mentioned above

**Comment by gabriel-gfs** [comment]
![Screenshot 2022-10-12 122217](https://user-images.githubusercontent.com/36446511/195319636-3614a065-e258-4367-b35b-2c010299552e.png)

**Comment by zackpollard** [comment]
Would you be able to provide that full set of photos so we have more of a dataset to test against?

**Comment by gabriel-gfs** [comment]
Sent it via Discord

**Comment by alextran1502** [comment]
Fixed in #1326

**Comment by gabriel-gfs** [comment]
> ![Screenshot 2022-10-12 122217](https://user-images.githubusercontent.com/36446511/195319636-3614a065-e258-4367-b35b-2c010299552e.png) As is probably visible in this there should be no sorting in which this is the correct order as the timestamps are all over the place

These pictures remain in incorrect order as you can see in this 
![image](https://user-images.githubusercontent.com/36446511/213400281-18c27641-85c6-448d-af91-52d15e10add6.png)

**Comment by alextran1502** [comment]
@gabriel-gfs 

Is this the new upload or from the original upload? The fix doesn't applied automatically to the older photos, only to the new upload. We are planning to add a new job to rescan all exif data

**Comment by gabriel-gfs** [comment]
No these are old pictures. Thanks for the information. I'll be looking forward to that job. 🤗
