### ISSUE TITLE
[BUG] Windows Docker-Desktop SMB Share not working or Network Drive

### ISSUE THREAD

**Issue by DevilsDesigns** [immich-app/immich#683]
**Describe the bug**
Im using docker-compose.yml and .env using docker desktop on windows 10. I added my path to my files in .env. But it wont show the files inside immich. I am hosting the files in samba share. I have a network drive with the photos and videos. Ive tried \\(ip-adress)\Google-Photos but it gives me an error no network path and wont start. But when i use a network drive letter ie M:\Media\Google-Photos it completes the running of `docker-compose up -d` but does not show any files inside the webui.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
Docker-Compose 
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    environment:
      - PUBLIC_TZ=${TZ}
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:80
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```

- [x] I have included my redacted `.env` file.
.Env
```
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432




###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=





###################################################################################
# Upload File Config
###################################################################################

UPLOAD_LOCATION=M:\Google-Photos



###################################################################################
# JWT SECRET
###################################################################################

JWT_SECRET=(MYSECRETPASS)




###################################################################################
# MAPBOX
####################################################################################

# ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=


####################################################################################
# WEB - Optional
####################################################################################

# Custom message on the login page, should be written in HTML form.
# For example PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"

PUBLIC_LOGIN_PAGE_MESSAGE="Welcome to Movies4You Memories Enjoy!"

# For correctly display your local time zone on the web, you can set the time zone here.
# Should work fine by default value, however, in case of incorrect timezone in EXIF, this value
# should be set to the correct timezone.
# Command to get timezone:
# - Linux: curl -s http://ip-api.com/json/ | grep -oP '(?<=timezone":")(.*?)(?=")' 

# TZ=Etc/UTC
```

- [ ] I have included information on my machine, and environment.
Windows 10
Docker-Desktop
CPU= Ryzen 5600G
RAM= 48GB 3000MHZ Dual Channel
**To Reproduce**
I cant find an error just a 

Error Log
```
level=warning msg="The \"TZ\" variable is not set. Defaulting to a blank string."
immich_postgres | 
immich_postgres | PostgreSQL Database directory appears to contain a database; Skipping initialization
immich_postgres | 
immich_postgres | 2022-09-13 05:30:25.224 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
immich_postgres | 2022-09-13 05:30:25.225 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
immich_postgres | 2022-09-13 05:30:25.226 UTC [1] LOG:  listening on IPv6 address "::", port 5432
immich_postgres | 2022-09-13 05:30:25.271 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
immich_postgres | 2022-09-13 05:30:25.303 UTC [26] LOG:  database system was shut down at 2022-09-13 05:28:56 UTC
immich_postgres | 2022-09-13 05:30:25.315 UTC [1] LOG:  database system is ready to accept connections
immich_redis | 1:C 13 Sep 2022 05:30:24.866 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
immich_redis | 1:C 13 Sep 2022 05:30:24.866 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
immich_redis | 1:C 13 Sep 2022 05:30:24.866 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
immich_redis | 1:M 13 Sep 2022 05:30:24.867 * monotonic clock: POSIX clock_gettime
immich_redis | 1:M 13 Sep 2022 05:30:24.867 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
immich_redis | 1:M 13 Sep 2022 05:30:24.867 * Running mode=standalone, port=6379.
immich_redis | 1:M 13 Sep 2022 05:30:24.867 # Server initialized
immich_redis | 1:M 13 Sep 2022 05:30:24.867 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
immich_redis | 1:M 13 Sep 2022 05:30:24.868 * Loading RDB produced by version 6.2.7
immich_redis | 1:M 13 Sep 2022 05:30:24.868 * RDB age 88 seconds
immich_redis | 1:M 13 Sep 2022 05:30:24.868 * RDB memory usage when created 0.79 Mb
immich_redis | 1:M 13 Sep 2022 05:30:24.868 # Done loading RDB, keys loaded: 1, keys expired: 0.
immich_redis | 1:M 13 Sep 2022 05:30:24.868 * DB loaded from disk: 0.000 seconds
immich_redis | 1:M 13 Sep 2022 05:30:24.868 * Ready to accept connections
immich_redis | 1:M 13 Sep 2022 05:39:31.228 * 100 changes in 300 seconds. Saving...
immich_redis | 1:M 13 Sep 2022 05:39:31.228 * Background saving started by pid 20
immich_redis | 20:C 13 Sep 2022 05:39:31.233 * DB saved on disk
immich_redis | 20:C 13 Sep 2022 05:39:31.234 * RDB: 0 MB of memory used by copy-on-write
immich_redis | 1:M 13 Sep 2022 05:39:31.329 * Background saving terminated with success
immich-app-immich-web-1 | Listening on 0.0.0.0:3000
response from daemon: configured logging driver does not support reading
```

**Expected behavior**
To Load all picture and photos in storage
**Screenshots**

**System**
- Server Version: `1.28.3`

**Additional context**
Im kinda of flying dark. i dont know much about this setup so any light that can be shed would be great

**Comment by bo0tzz** [comment]
Are you pointing Immich at a folder that already has files in it? That won't work. Instead, you need to upload files via one of the clients (mobile, web, or cli).

**Comment by sid8840** [comment]
> Are you pointing Immich at a folder that already has files in it? That won't work. Instead, you need to upload files via one of the clients (mobile, web, or cli).

thats not true. it does scan the folder with files already inside. when you add the library in it and scan it, it start the importing. as OP said, its still a problem with network drive permission with docker desktop and network samba share.

**Comment by bo0tzz** [comment]
You're talking about external libraries, which didn't even exist at the time this issue was created...

**Comment by sid8840** [comment]
> You're talking about external libraries, which didn't even exist at the time this issue was created...

anyway i have solved my remote nas mounting issue by following this url
https://technotim.com/posts/immich-self-hosted/
