### ISSUE TITLE
[BUG] Client Backup not working and Images not showing up in main view

### ISSUE THREAD

**Issue by gabriel-gfs** [immich-app/immich#835]
**Describe the bug**
The backup, neither the manual or the background one, work properly since the 13/10/2022. The remainder Number stays the same while immich tries to backup over and over again.
**Task List**
This worked before the newest release [v1.32.0_50-dev](https://github.com/immich-app/immich/releases/tag/v1.32.0_50-dev).

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included information on my machine, and environment.

```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:latest
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```

**To Reproduce**
1. Go to Backup in the app
2. Click on start Backup
3. The pictures get uploaded but nothing happens

**Expected behavior**
Backup works normally

**Screenshots**
![Screenshot_20221017_114622](https://user-images.githubusercontent.com/36446511/196146345-3e8bbda9-f6ea-49e4-991c-860e61437b24.jpg)
Also this Error occurs when the background service tries the same:
![image](https://user-images.githubusercontent.com/36446511/196146610-7d530722-3f8e-4ed8-94fc-654048c928f9.png)

**System**
- Phone OS [iOS, Android]: Android 12L
- Server Version: v1.32.0_50-dev
- Mobile App Version: 1.32.0 Build 50

**Additional context**
None of the logs(server, microservice, db, redis, etc. ) contain any errors.

**Comment by alextran1502** [comment]
I see the problem now... you are using the `latest` tag for the immich-server. Please change it to `release`

**Comment by gabriel-gfs** [comment]
I updated the docker compose but that doesnt fix the issue

**Comment by alextran1502** [comment]
Just to confirm, you did docker-compose pull immich-server after updating the content, correct? 

Do you have a way to spin up a fresh instance of Immich to try upload? I want to narrow down where does the error coming from, i.e. client or server

**Comment by gabriel-gfs** [comment]
Closing this issue because apparently I am at fault since i had some weird stuff going on in my network and after fixing that immich is back to working normal.
