### ISSUE TITLE
Versioned deployments for documentation site

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#9642]
Currently, cloudflare pages automatically pulls and deploys the documentation site on every commit to `main`. This has been an annoyance with needing to hold off on merging documentation PRs until after a release to avoid confusion. This issue lays out a path to resolve this and pick up a few other shiny things along the way.

The plan is to have the following deployments on cloudflare pages (they call each a "branch"). Each of these lives on its own subdomain under `immich.pages.dev`.
* `feat-foo`, deployed for every PR that makes changes to `docs/*`.
* `main`, deployed for every push to main that makes changes to `docs/*`.
* `vfoo` and `release`, deployed in the release workflow.

We manually set up custom domains in CF pages for `immich.app` -> `release.immich.pages.dev` and `main.immich.app` -> `main.immich.pages.dev`. All other deployments are accessed directly on the pages.dev hosts.

```[tasklist]
### Tasks
- [x] Deploy docs site from github actions with https://github.com/cloudflare/pages-action
- [x] Deploy docs site to `main`, `release`, etc on the appropriate events
- [x] Custom domains configured for release and main branch deployments
- [x] Push to preview branches on PR
- [x] Version switcher in documentation site
- [x] Version switcher automatically includes all existing versions
```
